version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    reviewers:
      - "Mostafa-SAID7"
    assignees:
      - "Mostafa-SAID7"
    labels:
      - "dependencies"
      - "automated"
    auto-merge:
      - match:
          update-types: ["patch", "minor"]
        auto-merge-action: "squash"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "docker"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
