# These are supported funding model platforms

github: 
  - Mostafa-SAID7

patreon: MostafaSaid

ko_fi: MostafaSaid

liberapay: MostafaSaid

issuehunt: MostafaSaid

buy_me_a_coffee: mssaid356p

thanks_dev: MostafaSaid
